# version: "3.8"
# services:
#   postgres:
#     image: postgres:16
#     container_name: neswear_postgres_server
#     environment:
#       POSTGRES_USER: ${PG_USER}
#       POSTGRES_PASSWORD: ${PG_PASSWORD}
#       POSTGRES_DB: ${PG_DB}
#     ports:
#       - "5433:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   minio:
#     image: minio/minio
#     container_name: minio_server
#     ports:
#       - "9000:9000"
#       - "9001:9001"
#     environment:
#       MINIO_ROOT_USER: ${MINIO_USER}
#       MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
#     command: server /data --console-address ":9001"
#     volumes:
#       - minio_data:/data

#   redis:
#     image: redis:7-alpine
#     container_name: neswear_redis_server
#     ports:
#       - "6379:6379"
#     volumes:
#       - redis_data:/data
#     command: redis-server --appendonly yes

#   backend:
#     build: .
#     ports:
#       - "3001:3001"
#     env_file:
#       - .env
#     depends_on:
#       - postgres
#       - redis
#       - minio

# volumes:
#   postgres_data:
#   minio_data:
#   redis_data:
